spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quan_ly_giang_vien
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

